sudo: true
language: python
matrix:
  include:
  - os: osx
    language: generic
  - os: linux
    python: "pypy"
  - os: linux
    python: "2.7"
  - os: linux
    python: "3.4"
  - os: linux
    python: "3.5"
  - os: linux
    python: "3.6"
install:
  - scripts/install-on-travis.sh
script:
  - scripts/run-on-travis.sh make check
  - scripts/run-on-travis.sh make test
after_success:
  - scripts/run-on-travis.sh coveralls
branches:
  except:
    - /^[0-9]/
